name: github pages

on:
  push:
    branches:
      - lina # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: curl, mbstring, zip, pcntl, pdo, iconv
          coverage: none

      - name: Install Line
        run: |
          composer global config minimum-stability dev
          composer global require bangnokia/lina:dev-main --prefer-dist

      - name: Build
        run: |
          ls -la
          php lina.phar build
          rm ./public/.gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          #cname: your-domain.com  # your custom domain
